apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- all-redis-operator-resources.yaml
- namespace.yaml
- prometheus/alertmanager-alertmanager.yaml
- prometheus/alertmanager-podDisruptionBudget.yaml
- prometheus/alertmanager-prometheusRule.yaml
- prometheus/alertmanager-secret.yaml
- prometheus/alertmanager-service.yaml
- prometheus/alertmanager-serviceAccount.yaml
- prometheus/alertmanager-serviceMonitor.yaml
- prometheus/blackbox-exporter-clusterRole.yaml
- prometheus/blackbox-exporter-clusterRoleBinding.yaml
- prometheus/blackbox-exporter-configuration.yaml
- prometheus/blackbox-exporter-deployment.yaml
- prometheus/blackbox-exporter-service.yaml
- prometheus/blackbox-exporter-serviceAccount.yaml
- prometheus/blackbox-exporter-serviceMonitor.yaml
- prometheus/grafana-dashboardDatasources.yaml
- prometheus/grafana-dashboardDefinitions.yaml
- prometheus/grafana-dashboardSources.yaml
- prometheus/grafana-deployment.yaml
- prometheus/grafana-service.yaml
- prometheus/grafana-serviceAccount.yaml
- prometheus/grafana-serviceMonitor.yaml
- prometheus/kube-prometheus-prometheusRule.yaml
- prometheus/kube-state-metrics-clusterRole.yaml
- prometheus/kube-state-metrics-clusterRoleBinding.yaml
- prometheus/kube-state-metrics-deployment.yaml
- prometheus/kube-state-metrics-prometheusRule.yaml
- prometheus/kube-state-metrics-service.yaml
- prometheus/kube-state-metrics-serviceAccount.yaml
- prometheus/kube-state-metrics-serviceMonitor.yaml
- prometheus/kubernetes-prometheusRule.yaml
- prometheus/kubernetes-serviceMonitorApiserver.yaml
- prometheus/kubernetes-serviceMonitorCoreDNS.yaml
- prometheus/kubernetes-serviceMonitorKubeControllerManager.yaml
- prometheus/kubernetes-serviceMonitorKubeScheduler.yaml
- prometheus/kubernetes-serviceMonitorKubelet.yaml
- prometheus/node-exporter-clusterRole.yaml
- prometheus/node-exporter-clusterRoleBinding.yaml
- prometheus/node-exporter-daemonset.yaml
- prometheus/node-exporter-prometheusRule.yaml
- prometheus/node-exporter-service.yaml
- prometheus/node-exporter-serviceAccount.yaml
- prometheus/node-exporter-serviceMonitor.yaml
- prometheus/prometheus-adapter-apiService.yaml
- prometheus/prometheus-adapter-clusterRole.yaml
- prometheus/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
- prometheus/prometheus-adapter-clusterRoleBinding.yaml
- prometheus/prometheus-adapter-clusterRoleBindingDelegator.yaml
- prometheus/prometheus-adapter-clusterRoleServerResources.yaml
- prometheus/prometheus-adapter-configMap.yaml
- prometheus/prometheus-adapter-deployment.yaml
- prometheus/prometheus-adapter-podDisruptionBudget.yaml
- prometheus/prometheus-adapter-roleBindingAuthReader.yaml
- prometheus/prometheus-adapter-service.yaml
- prometheus/prometheus-adapter-serviceAccount.yaml
- prometheus/prometheus-adapter-serviceMonitor.yaml
- prometheus/prometheus-clusterRole.yaml
- prometheus/prometheus-clusterRoleBinding.yaml
- prometheus/prometheus-operator-prometheusRule.yaml
- prometheus/prometheus-operator-serviceMonitor.yaml
- prometheus/prometheus-podDisruptionBudget.yaml
- prometheus/prometheus-prometheus.yaml
- prometheus/prometheus-prometheusRule.yaml
- prometheus/prometheus-roleBindingConfig.yaml
- prometheus/prometheus-roleBindingSpecificNamespaces.yaml
- prometheus/prometheus-roleConfig.yaml
- prometheus/prometheus-roleSpecificNamespaces.yaml
- prometheus/prometheus-service.yaml
- prometheus/prometheus-serviceAccount.yaml
- prometheus/prometheus-serviceMonitor.yaml
- prometheus/setup/0namespace-namespace.yaml
- prometheus/setup/prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0probeCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- prometheus/setup/prometheus-operator-clusterRole.yaml
- prometheus/setup/prometheus-operator-clusterRoleBinding.yaml
- prometheus/setup/prometheus-operator-deployment.yaml
- prometheus/setup/prometheus-operator-service.yaml
- prometheus/setup/prometheus-operator-serviceAccount.yaml
- redis.yaml
